### PR TITLE
Pkg.thrift

### PR DESCRIPTION
**Pull request by isaachier**

### CODE REVIEW

**Comment by isaachier** [comment]
This looks really strange. Hope the other files don't matter too much. Just changing Travis and AppVeyor configs.

**Comment by ruslo** [comment]
> This looks really strange

I guess this is because `pkg.thrift` was out-of-date. I've pushed new changes, please rebase.

**Comment by isaachier** [comment]
Much better now.

**Review by ruslo — CHANGES_REQUESTED** [review]
If you want to enable new toolchains you should send fixed version first:
* https://docs.hunter.sh/en/latest/creating-new/update.html#add-toolchains

**Comment by isaachier** [comment]
OK. The new version is on https://github.com/ruslo/hunter repo for your review.

**Comment by ruslo** [comment]
> OK. The new version is on https://github.com/ruslo/hunter repo for your review

Open new pull request when it will be merged.

**Pull request closed without merging**
