### PR TITLE
Package ethash: disable ios-nocodesign-11-3-dep-9-3 config

### PR DESCRIPTION
**Pull request by chfast**
* I have checked that this pull request contains only
  `.travis.yml`/`appveyor.yml` changes. All other changes send
  to https://github.com/ruslo/hunter. **[Yes]**

* I have checked that no toolchains removed from CI configs, they are commented
  out instead so other developers can enable them back easily and to simplify
  merge conflict resolution. **[Yes]**

* I have checked that for every commented out toolchain there is a link to the
  broken CI build page or to the minimum compiler requirements documentation
  so other developers can figure out what was the problem exactly. **[Yes]**

### CODE REVIEW

**Comment by chfast** [comment]
Also branch `pgk.ethash` has a typo in the name.

**Comment by chfast** [comment]
Wait. I will add some arm toolchains.

**Review by ruslo — CHANGES_REQUESTED** [review]
> Also branch pgk.ethash has a typo in the name.

Fixed

> Wait. I will add some arm toolchains.

Ok

**Comment by chfast** [comment]
Done.

**Review by ruslo — APPROVED** [review]

**Pull request merged**
