### PR TITLE
Pkg.suitesparse with dynamic LAPACK

### PR DESCRIPTION
**Pull request by NeroBurner**
- merge branch neroburner/LAPACK-dynamic
- add example SuiteSparse-dynLAPACK

### CODE REVIEW

**Comment by ruslo** [comment]
pkg.suitesparse updated, please rebase.

**Comment by NeroBurner** [comment]
rebased

**Review by ruslo — APPROVED** [review]

**Comment by ruslo** [comment]
All new tests failed.

**Comment by NeroBurner** [comment]
the new builds try to build LAPACK, but in the SuiteSparse test no gfortran compiler is installed. Is it ok if I install it as dependency?

Edit: now only Android toolchain should fail, like over here https://github.com/ingenue/hunter/pull/119#issuecomment-326682988

**Comment by NeroBurner** [comment]
Apple can't find Fortran compiler
```
CMake Error at CMakeLists.txt:11 (project):
  No CMAKE_Fortran_COMPILER could be found.
  Tell CMake where to find the compiler by setting either the environment
  variable "FC" or the CMake cache entry CMAKE_Fortran_COMPILER to the full
  path to the compiler, or to the compiler name if it is in the PATH.
```

Linux has logs which are too long
```
The log length has exceeded the limit of 4 MB (this usually means that the test suite is raising the same exception over and over).

The job has been terminated
```

**Comment by ruslo** [comment]
> Apple can't find Fortran compiler

Add this code:
https://github.com/ingenue/hunter/blob/b0ca33d284d0571fb5a4b1b2ca62b1e23e17645b/.travis.yml#L138-L139

> Linux has logs which are too long

Add code like this to `jenkins.py`:
https://github.com/ingenue/hunter/blob/7b216ca91c38bafa684238f3b5d8cd9c61ea2ab1/jenkins.py#L128-L133

Also probably after LAPACK upload this error will go away.

**Comment by NeroBurner** [comment]
addad your changes

the script `jenkins.py` has a flag `--verbose`, but this flag is never used. Maybe we could add a flag `--cropped` or `--short-log` or  `--crop-output` instead of changing `jenkins.py` for each project which generates too much output

**Comment by ruslo** [comment]
It will be easier to add VERBOSE=1 environment variable to CI config and read it in `jenkins.py`.

**Comment by NeroBurner** [comment]
~~could you update the branch `upload.suitesparse` to upload the binaries for msvc. Then I can add the toolchain to `ceres-solver` without fear of log to long errors~~

edit: sorry wrong PR

**Pull request merged**
