### PR TITLE
Testing for "state_machine" package

### PR DESCRIPTION
**Pull request by NukeBird**

### CODE REVIEW

**Comment by ruslo** [comment]
Have you tested this? It's pretty rare when all toolchains are working. I expect something excluded:
* https://docs.hunter.sh/en/latest/creating-new/create/cmake.html#excluding-tests

**Comment by NukeBird** [comment]
@ruslo no I didn't. But why only default test failed?
https://travis-ci.org/ingenue/hunter/jobs/299829219

**Comment by NukeBird** [comment]
@ruslo I exclude default test, but nothing changes https://github.com/NukeBird/hunter/commit/cd2e226c4d5711273ede372102f3921a66e07e91
https://travis-ci.org/NukeBird/hunter/jobs/297699368

**Comment by NukeBird** [comment]
It looks like, well, c++11 missed

But I can't understand WHY default test still exist?

**Comment by ruslo** [comment]
> but nothing changes

What do you expect to changed? Excluding toolchain remove `default` entry from CI matrix.

> It looks like, well, c++11 missed

Toolchain `default` doesn't add any extra flags, that's the point of name :)

> But I can't understand WHY default test still exist?

It's just one of the toolchains to test. Not sure how to answer that :) Why Android toolchains exist?

**Comment by NukeBird** [comment]
Oh, well, something wrong with .travis.yml...:
https://travis-ci.org/NukeBird/hunter/builds/300115389

> ERROR: An error occured while trying to parse your .travis.yml file.

**Comment by NukeBird** [comment]
> 1.05s$ rake
> rake aborted!
> No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)

**Comment by ruslo** [comment]
Probably it doesn't like TABS you've added.

**Comment by NukeBird** [comment]
> Probably it doesn't like TABS you've added.

Okay, I'll try without them

**Comment by NukeBird** [comment]
https://github.com/ingenue/hunter/pull/158

**Pull request merged**
