### PR TITLE
removed appveyor failing tests for odb-boost

### PR DESCRIPTION
**Pull request by pretyman**

### CODE REVIEW

**Comment by ruslo** [comment]
I've pushed updates from `develop`, please rebase

**Comment by pretyman** [comment]
Ok, done :+1:

**Comment by pretyman** [comment]
Updated: removed travis broken tests

**Comment by ruslo** [comment]
> Updated: removed travis broken tests

Thanks, now need a patience to wait for all of this stuff finish testing :sleeping: :alarm_clock:

**Pull request merged**
