### PR TITLE
Pkg.ceres solver add toolchain linux-mingw-w64-cxx98

### PR DESCRIPTION
**Pull request by NeroBurner**
add cross compiling toolchain linux-mingw-w64-cxx98

the toolchain  linux-mingw-w64 is not working, because bessel functions are not definded if `__STRICT_ANSI__` is definded. And this flag gets defined with `-std=c++11`

https://sourceforge.net/p/mingw-w64/feature-requests/68/

> In MinGW, the Bessel functions (j0, j1, jn, y0, y1, yn) are only defined when `__STRICT_ANSI__` is not defined. In glibc, they're defined when `_BSD_SOURCE` or `_XOPEN_SOURCE` is defined. It would be nice if this was also the case in MinGW, so programs could use them without undefining `__STRICT_ANSI__`.

### CODE REVIEW

**Comment by ruslo** [comment]
`linux-mingw-*` toolchain failed

**Comment by NeroBurner** [comment]
forgot to install mingw-w64 for the toolchain

**Comment by ruslo** [comment]
Still failing.

**Comment by NeroBurner** [comment]
oh, I didn't see that
```
error: conflicting declaration ‘typedef DWORD pthread_t’

 typedef DWORD pthread_t;
```

This should be fixed with https://github.com/ruslo/hunter/pull/1006 (update to glog 0.3.5-p1)

**Review by ruslo — CHANGES_REQUESTED** [review]
Only `.travis.yml`/`appveyor.yml` updates.

**Comment by ruslo** [comment]
Closing inactive pull request

**Pull request closed without merging**
