### PR TITLE
PostgreSQL: Remove Android comments

### PR DESCRIPTION
**Pull request by xsacha**

### CODE REVIEW

**Comment by ruslo** [comment]
Seems like nothing fixed :( Have you tested the change before?

**Comment by xsacha** [comment]
I tested with change in my local Hunter/config.cmake instead so I forgot about the include required in cmake/projects.
Needs a rebase on fix.

**Comment by ruslo** [comment]
> I tested with change in my local Hunter/config.cmake instead

You can use [jenkins.py](https://github.com/ruslo/hunter/wiki/dev.hunter.root#jenkinspy) way of testing to avoid such issues.

**Comment by xsacha** [comment]
Ah, I see! Thanks!

**Comment by xsacha** [comment]
Looks like redefinition of random() with that NDK. I'm using latest NDK which has proper random header.
Not sure what best solution is. Detect version and define HAVE_RANDOM?

**Comment by ruslo** [comment]
> I'm using latest NDK which has proper random header.

If updating NDK helps then this is a solution. Old NDK was not working anyway.

**Review by ruslo — CHANGES_REQUESTED** [review]
.

**Comment by xsacha** [comment]
I am not sure where install-ci-dependencies is. I tried to add a newer NDK but it isn't installed.

To fix ndk 10/11, the random function needs to be found by configure (to set HAVE_RANDOM and not add random.o to objects) but I can't see a way of doing this.

**Comment by ruslo** [comment]
> I am not sure where install-ci-dependencies is

It's a helper script from Polly:
* https://github.com/ruslo/polly/tree/master/bin

> I tried to add a newer NDK but it isn't installed

It's not added yet:
* https://github.com/ruslo/polly/blob/d0b738b7ba79727e6ccf399ff2924f5ddba6058b/bin/install-ci-dependencies.py#L126-L139

Toolchain can be used on local machine. For Travis I have to create pruned version of NDK since full version is quite heavy (see https://github.com/hunter-packages/android-ndk). If you want this toolchain to work on Travis CI please open [Polly](https://github.com/ruslo/polly) issue first.

> To fix ndk 10/11, the random function needs to be found by configure (to set HAVE_RANDOM and not add random.o to objects) but I can't see a way of doing this

Sounds like an upstream issue.

**Comment by ruslo** [comment]
Closing inactive pull request

**Pull request closed without merging**
