### PR TITLE
Testing for the 'tacopie' package

### PR DESCRIPTION
**Pull request by krzysztof-cywinski**
* I have checked that this pull request contains only
  `.travis.yml`/`appveyor.yml` changes. All other changes send
  to https://github.com/ruslo/hunter. **Yes**

* I have checked that no toolchains removed from CI configs, they are commented
  out instead so other developers can enable them back easily and to simplify
  merge conflict resolution. **Yes**

* I have checked that for every commented out toolchain there is a link to the
  broken CI build page or to the minimum compiler requirements documentation
  so other developers can figure out what was the problem exactly. **Yes**

### CODE REVIEW

**Comment by krzysztof-cywinski** [comment]
Hi @ruslo 
There's been some kind of a mixup. I must have missed the pkg.tacopie branch in this repo before.
I noticed you marked most of the toolchains as broken. This is actually the reason behind this update.
I bumped the package to v.3.2.0 that builds correctly with the new toolchains.
The updated CI build urls are:
- travis: https://travis-ci.org/szatan/hunter/builds/382361625
- appveyor: https://ci.appveyor.com/project/szatan/hunter/build/1.0.8
Hopefully this fixes it. Thanks.

**Comment by ruslo** [comment]
> Testing for the 'tacopie' package

`pkg.tacopie` already exists so it should be updated instead of created from scratch. I have pushed new toolchains to `pkg.tacopie` branch and excluded broken builds. Most of them don't match because tacopie is not working with C++17.

If you want to introduce any new changes please set pkg.tacopie as a target branch:
* https://github.com/ingenue/hunter/tree/pkg.tacopie

**Comment by ruslo** [comment]
> I bumped the package to v.3.2.0 that builds correctly with the new toolchains.

@szatan That is great, let's test it with old toolchains first then add new toolchains to the CI matrix. See:
* https://docs.hunter.sh/en/latest/creating-new/update.html#add-toolchains

**Comment by krzysztof-cywinski** [comment]
@ruslo thanks for the info. I'll give it another go tommorrow morning.

**Pull request closed without merging**
