### PR TITLE
Pkg.ceres solver add dyn lapack test

### PR DESCRIPTION
**Pull request by NeroBurner**

### CODE REVIEW

**Comment by ruslo** [comment]
I don't see any builds, probably because you choose `pkg.template` as target first. Try to rebase your change.

**Comment by NeroBurner** [comment]
now it's building

**Review by ruslo — APPROVED** [review]

**Comment by ruslo** [comment]
```
The log length has exceeded the limit of 4 MB (this usually means that the test suite is raising the same exception over and over).
The job has been terminated
```

Use this pattern in `jenkins.py` to enable `verbose=False`:
```  if (
      os.getenv('TRAVIS') and
      (project_dir == 'examples/CLAPACK') and
      (toolchain == 'xcode')
  ):
    verbose = False
```

**Comment by NeroBurner** [comment]
another way would be to add examples for LAPACK_dynamic and SuiteSparse_dynLAPACK. Then the logs would be shorter again. What do you think would be better?

**Comment by ruslo** [comment]
> another way would be to add examples for LAPACK_dynamic and SuiteSparse_dynLAPACK

You mean because we will get binaries from cache instead of building? Yes, may work.

**Comment by NeroBurner** [comment]
let's test it :)

added two builds:
- LAPACK-dynamic https://github.com/ingenue/hunter/pull/119
- SuiteSparse-dynLAPACK https://github.com/ingenue/hunter/pull/120

the PRs are not intended to be merged. They are just that travis builds are started and tested. The master branch should be merged (after merging the examples-PRs) into `pkg.lapack` and `pkg.suitesparse`. Then only the last commit of the pull requests (mentioned above) is needed

**Comment by ruslo** [comment]
> the PRs are not intended to be merged

If we need binaries from cache we need to test new `.travis.yml`/`appveyor.yml` first, then I will merge and update `upload.*` branches. When upload done we can run tests from this pull request and see if it helps.

**Comment by ruslo** [comment]
Closing inactive pull request

**Pull request closed without merging**
