### PR TITLE
SuiteSparse: remove failing builds

### PR DESCRIPTION
**Pull request by NeroBurner**

### CODE REVIEW

**Comment by NeroBurner** [comment]
@ruslo somehow I did the remove of failing builds wrong again

**Comment by ruslo** [comment]
> @ruslo somehow I did the remove of failing builds wrong again

What do you mean? Looks good.

**Comment by NeroBurner** [comment]
It seemed to me that the tests were all failing. Must have been a wrong link or something

**Comment by ruslo** [comment]
Pull request with `suitesparse` was not merged at the time you've submitted patch, all tests in `pkg.suitesparse` was not working. Update is `RED` -> `RED`.

**Pull request merged**
