### PR TITLE
Pkg.glog update toolchains and reenable

### PR DESCRIPTION
**Pull request by NeroBurner**
* I have checked that this pull request contains only
  `.travis.yml`/`appveyor.yml` changes. All other changes send
  to https://github.com/ruslo/hunter. **[Yes]**

* I have checked that no toolchains removed from CI configs, they are commented
  out instead so other developers can enable them back easily and to simplify
  merge conflict resolution. **[Yes]**

* I have checked that for every commented out toolchain there is a link to the
  broken CI build page or to the minimum compiler requirements documentation
  so other developers can figure out what was the problem exactly. **[Yes]**

reenabled toolchains:
- analyze-cxx17
- sanitize-address-cxx17
- sanitize-leak-cxx17

ci links:
- travis: https://travis-ci.org/NeroBurner/hunter/builds/466517924
- appveyor: https://ci.appveyor.com/project/NeroBurner/hunter/builds/20926719

### CODE REVIEW

**Comment by ruslo** [comment]
> @ruslo ruslo merged commit ff8b269 into ingenue:pkg.template 5 minutes ago

Wrong branch :)

Pushed to https://github.com/ingenue/hunter/commits/pkg.glog

Tests:
* https://ci.appveyor.com/project/ingenue/hunter/builds/20928720
* https://travis-ci.org/ingenue/hunter/builds/466539220?utm_source=github_status&utm_medium=notification

**Comment by NeroBurner** [comment]
sorry :see_no_evil: and thanks :)

**Comment by NeroBurner** [comment]
@ruslo Could you also run the upload.glog branch for this branch and eigen? I'm runnung in the 60minute timeoutbwhen testing ceres-solver 1.14 on MSVC2017 and I hope I get that down under one hour when glog and eigen are in the package cache

edit: no need for `upload.eigen`. A new version of eigen (3.3.7) is incoming

**Comment by ruslo** [comment]
> Could you also run the upload.glog branch for this branch and eigen?

* https://ci.appveyor.com/project/ingenue/hunter/builds/20953227
* https://travis-ci.org/ingenue/hunter/builds/466948501?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
> Could you also run the upload.glog branch for this branch

`upload.glog` is ready

**Comment by NeroBurner** [comment]
thanks a lot :)

**Pull request merged**
