### PR TITLE
Pkg.lapack dynamic

### PR DESCRIPTION
**Pull request by NeroBurner**
- merge branch neroburner/LAPACK-dynamic
- add example LAPACK-dynamic

### CODE REVIEW

**Comment by ruslo** [comment]
pkg.lapack updated, please rebase.

**Comment by NeroBurner** [comment]
rebased

**Review by ruslo — APPROVED** [review]

**Comment by ruslo** [comment]
Android toolchain failed.

**Comment by NeroBurner** [comment]
> Android toolchain failed.

- `gfortran-4.8 amd64 4.8.4-2ubuntu1~14.04.3` is installed
- `Check for working Fortran compiler: /usr/bin/f95` is used as Fortran compiler
- `arm-linux-androideabi-g++` is used as C++ compiler
- something like `arm-linux-androideabi-gfortran` should be used as Fortran compiler

I don't see any reference to compiler definitions in the toolchain files. I think that gfortran for arm-linux-androideabi is either not available, or not defined in the toolchain file.

Toolchain:
https://github.com/ruslo/polly/blob/master/android-ndk-r10e-api-19-armeabi-v7a-neon.cmake

Polly android definition file:
https://github.com/ruslo/polly/blob/master/os/android.cmake

**Comment by ruslo** [comment]
Not a Fortran user. If you don't know how to fix it - just exclude it.

**Comment by NeroBurner** [comment]
is there a way to check if a gfortran compiler is available for the android ndks? If there is already a gfortran compiler included (or easily obtainable) we could just set the variable `CMAKE_Fortran_ANDROID_TOOLCHAIN_PREFIX` appropriately (I think)

https://cmake.org/cmake/help/v3.7/manual/cmake-toolchains.7.html#cross-compiling-for-android

**Comment by ruslo** [comment]
There are no files in Android NDK that match "fortran" pattern.

**Comment by NeroBurner** [comment]
removed android builds, because there is no android Fortran compiler

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2329
* https://travis-ci.org/ingenue/hunter/builds/271693853?utm_source=github_status&utm_medium=notification

**Pull request merged**
