### PR TITLE
LAPACK: fix testing

### PR DESCRIPTION
**Pull request by NeroBurner**
- add gfortran package

### CODE REVIEW

**Comment by NeroBurner** [comment]
why do I get the error with travis
```
CMake Error: The source directory "/home/travis/build/ingenue/hunter/examples/LAPACK" does not exist.
```

**Comment by ruslo** [comment]
Added here:
* https://github.com/ingenue/hunter/commit/03b529c48ec831cd1d70fa7425fb9b3da00e64c4

Testing results:
* https://travis-ci.org/ingenue/hunter/builds/249601286?utm_source=github_status&utm_medium=notification
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1908

> why do I get the error with travis

Pull request https://github.com/ruslo/hunter/pull/860 is still opened so example is not in the main testing branch yet. It's okay.

**Comment by NeroBurner** [comment]
do I open another pull request to disable the failing toolchains, or how to proceed?

**Comment by ruslo** [comment]
It's up to you. You can close this one and open new or push new changes here. Just don't forget to rebase and squash. Current patch is out of date.

**Comment by NeroBurner** [comment]
rebased, disabled failing builds, enable linux-mingw-w64 buids

**Comment by ruslo** [comment]
> enable linux-mingw-w64 buids

Disabling tests is fine because it move from `RED` to `RED` state. Enabling require to have LAPACK merged in main branch. Allowed only `GREEN` to `GREEN` move.

**Comment by NeroBurner** [comment]
removed the commit enabling linux-mingw-w64

**Comment by xsacha** [comment]
Just wondering: how does /usr/bin/f95 from gfortran package compile for Android?
See: https://travis-ci.org/ingenue/hunter/jobs/250702379

It seems to link successfully in hunter tests but it gives me an x86_64 binary when I do it myself.
By the way, OpenBLAS package does this too and silently fails in my other packages that use it (dlib).

**Comment by ruslo** [comment]
> It seems to link successfully in hunter tests but it gives me an x86_64 binary when I do it myself

Are you saying that this command produce x86_64 binary?

```
/home/travis/build/ingenue/hunter/_ci/android-ndk-r10e/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-g++
    --sysroot=/home/travis/build/ingenue/hunter/_ci/android-ndk-r10e/platforms/android-19/arch-arm
    -std=c++11
    -march=armv7-a
    -marm
    -mfpu=neon
    -mfloat-abi=softfp
    -funwind-tables
    -no-canonical-prefixes
    -fexceptions
    -frtti
    -O3
    -DNDEBUG
    -Wl,--fix-cortex-a8
    -fPIE
    -pie
    -Wl,--gc-sections
    -Wl,-z,nocopyreloc
    CMakeFiles/foo.dir/foo.cpp.o
    -o foo
    /home/travis/build/ingenue/hunter/_testing/Hunter/_Base/9529eb0/11091a0/5813733/Install/lib/libblas.a
    /home/travis/build/ingenue/hunter/_testing/Hunter/_Base/9529eb0/11091a0/5813733/Install/lib/liblapack.a
    /home/travis/build/ingenue/hunter/_testing/Hunter/_Base/9529eb0/11091a0/5813733/Install/lib/libblas.a
    "/home/travis/build/ingenue/hunter/_ci/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/libgnustl_static.a"
```

**Comment by xsacha** [comment]
No, that looks like ARM but the lapack library (which is created with Fortran) is x86_64.

**Comment by xsacha** [comment]
It looks like only CBLAS is tested in example?
https://github.com/ruslo/hunter/blob/master/examples/LAPACK-CBLAS/foo.cpp

**Comment by NeroBurner** [comment]
maybe we need to specify the gfortran cross compiler
https://packages.ubuntu.com/artful/devel/gfortran-arm-linux-gnueabihf

I'm not familiar with the android toolchain

**Comment by ruslo** [comment]
Let's start with example which can help with reproducing issue. It's not clear for me where is the error.

**Comment by xsacha** [comment]
Problem is just that it finds and uses host Fortran compiler when compiling for Android.

**Comment by ruslo** [comment]
It's good that you know the reason already :) However we need to have an example to test the state of the issue.

**Pull request merged**
