### PR TITLE
add linux-mingw cross compile toolchain

### PR DESCRIPTION
**Pull request by NeroBurner**
I don't know where to add `sudo apt-get install mingw-w64 g++-mingw-w64`

### CODE REVIEW

**Comment by ruslo** [comment]
https://github.com/travis-ci-tester/travis-test-mingw/blob/fc6c6b8ef6ee9ece205ea9224ce05bf7ba99a6b4/.travis.yml#L16-L19

**Comment by NeroBurner** [comment]
I think I somehow broke travis

**Comment by ruslo** [comment]
I've cancelled the build to free CI machines. We have nothing to test here until https://github.com/ruslo/hunter/pull/846 merged.

**Comment by NeroBurner** [comment]
ah, ok
Is there something I have to do to get the mingw cross compilation patch in?

**Comment by ruslo** [comment]
See this comment:
* https://github.com/ruslo/hunter/pull/846/files#r123256400

**Comment by NeroBurner** [comment]
with https://github.com/ruslo/hunter/pull/846 merged can we get mingw-w64 cross compile toolchain integrated? :)

**Comment by ruslo** [comment]
Yes, I think you need to rebase your patch.

**Comment by NeroBurner** [comment]
rebased and squashed into two commits

**Comment by ruslo** [comment]
Boost.iostreams failed

**Comment by NeroBurner** [comment]
gzip and bzip2 are included, but not provieded by hunter

https://github.com/ruslo/hunter/blob/master/examples/Boost-iostreams/foo.cpp#L9

in `BoostBZip2Dependency.cmake` I've found the following comment
```
# Do not call 'hunter_add_package(BZip2)' because BZip2 it not a basic dependency
find_package(BZip2 CONFIG REQUIRED)
```

I suspect that at the other build targets bzip2 or zlib are found in the system. But there is no windows zlib dll installed at the buildmachine

**Comment by ruslo** [comment]
BZip2 installation logic is here:
* https://github.com/ruslo/hunter/blob/f40019870daa5da8786952fa5d6edbaee0b7f64b/cmake/modules/hunter_boost_component_b2_args.cmake#L127-L129

**Comment by ruslo** [comment]
Closing inactive pull request

**Pull request closed without merging**
