### PR TITLE
Rebase pkg.rocksdb

### PR DESCRIPTION
**Pull request by chfast**
* I have checked that this pull request contains only
  `.travis.yml`/`appveyor.yml` changes. All other changes send
  to https://github.com/ruslo/hunter. **[Yes]**

* I have checked that no toolchains removed from CI configs, they are commented
  out instead so other developers can enable them back easily and to simplify
  merge conflict resolution. **[No]**

* I have checked that for every commented out toolchain there is a link to the
  broken CI build page or to the minimum compiler requirements documentation
  so other developers can figure out what was the problem exactly. **[No]**

* I have checked that for every enabled toolchain corresponding package passed
  all stages of update cycle: test/merge/upload/release. **[No]**

### CODE REVIEW

**Review by ruslo — CHANGES_REQUESTED** [review]
Seems that all windows tests failed, as well as some Travis tests.

**Comment by chfast** [comment]
I took the config from pkg.template to check what's still failing. The Windows was never working, but I hope to fix it later on.

**Comment by ruslo** [comment]
Set of toolchains updated:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.3642
* https://travis-ci.org/ingenue/hunter/builds/367765204?utm_source=github_status&utm_medium=notification

**Comment by chfast** [comment]
Can I close it now?

**Pull request closed without merging**
