### PR TITLE
Pkg.openssl

### PR DESCRIPTION
**Pull request by xsacha**
Analyze: Was always using wrong compiler, now broken with correct compiler.
Android: Changed build links because old link did not show any error

### CODE REVIEW

**Comment by ruslo** [comment]
Please do clean-up. This pull request should only affect `.travis.yml` and/or `appveyor.yml`. See top-level README: https://github.com/ingenue/hunter

**Comment by xsacha** [comment]
Sorry, I pulled from pkg.openssl.pr-534
I'll rebase

**Comment by xsacha** [comment]
Rebased

**Comment by xsacha** [comment]
It got:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk not exists

but I don't think that's related to this pull request. It worked earlier.

**Comment by ruslo** [comment]
> but I don't think that's related to this pull request. It worked earlier.

Yes, Travis team updated default OSX environment yesterday:
- https://blog.travis-ci.com/2016-10-04-osx-73-default-image-live/

Now it's `osx-10-11` instead of `osx-10-9`. I will apply necessary updates for OpenSSL configs.

**Pull request merged**
