### PR TITLE
Remove broken toolchain for new Thrift release

### PR DESCRIPTION
**Pull request by isaachier**
* I have checked that this pull request contains only
  `.travis.yml`/`appveyor.yml` changes. All other changes send
  to https://github.com/ruslo/hunter. **Yes**

* I have checked that no toolchains removed from CI configs, they are commented
  out instead so other developers can enable them back easily and to simplify
  merge conflict resolution. **Yes**

* I have checked that for every commented out toolchain there is a link to the
  broken CI build page or to the minimum compiler requirements documentation
  so other developers can figure out what was the problem exactly. **Yes**

* I have checked that for every enabled toolchain corresponding package passed
  all stages of update cycle: test/merge/upload/release. **Yes**

### CODE REVIEW

**Review by ruslo — CHANGES_REQUESTED** [review]
As far as I can see MinGW is not working.

**Comment by isaachier** [comment]
OK so I am updating toolchains AND package. As of now, I assume a lot of these don't work. I'm guessing I need to upgrade toolchain to set that works with new and old, then upgrade Thrift, then expand the set to include new working toolchains.

**Comment by isaachier** [comment]
Well this is what happens when I try merging my new toolchains onto master.

https://travis-ci.org/isaachier/hunter/builds/371281360
https://ci.appveyor.com/project/isaachier/hunter/build/1.0.464

**Comment by ruslo** [comment]
Upgrade toolchains to "All passed" state, then push new version, then enable new toolchain if any:
* https://docs.hunter.sh/en/latest/creating-new/update.html#add-toolchains

**Comment by isaachier** [comment]
Right but every single new toolchain fails for current Thrift.

**Comment by ruslo** [comment]
> Right but every single new toolchain fails for current Thrift.

You can exclude new set and add old toolchains in `# Extra {` / `# }` block.

**Comment by isaachier** [comment]
@ruslo if you look [here](https://travis-ci.org/isaachier/hunter/builds/371375344) the issue is about some passwords file, not the compilation.

> [hunter ** FATAL ERROR **] File with passwords not found: '/home/travis/.config/Hunter/passwords.cmake'

**Comment by ruslo** [comment]
I have fixed it recently, pull commits from master.

**Comment by isaachier** [comment]
Great, seems to have fix [this](https://travis-ci.org/isaachier/hunter/builds/371604162).

**Comment by isaachier** [comment]
OK I'm closing this as unnecessary.

**Comment by ruslo** [comment]
> OK I'm closing this as unnecessary.

Unnecessary? Well at least it make sense to update CI toolchain set.

Testing:
* https://travis-ci.org/ingenue/hunter/builds/372225210?utm_source=github_status&utm_medium=notification

**Comment by isaachier** [comment]
Actually... My mistake. It seems I need to remove the osx-10-11 build as this review does.

**Comment by ruslo** [comment]
> There are no new changes to show

I've already pushed new toolchains to branch `pkg.thrift`.

**Comment by isaachier** [comment]
Awesome I'll just close this then.

**Pull request closed without merging**
