### PR TITLE
Pkg.eigen

### PR DESCRIPTION
**Pull request by NeroBurner**
* I have checked that this pull request contains only
  `.travis.yml`/`appveyor.yml` changes. All other changes send
  to https://github.com/ruslo/hunter. **[Yes]**

* I have checked that no toolchains removed from CI configs, they are commented
  out instead so other developers can enable them back easily and to simplify
  merge conflict resolution. **[Yes]**

* I have checked that for every commented out toolchain there is a link to the
  broken CI build page or to the minimum compiler requirements documentation
  so other developers can figure out what was the problem exactly. **[Yes]**

merge `pkg.template` to update package cache

### CODE REVIEW

**Comment by NeroBurner** [comment]
sorry, I was too fast with the PR, need to wait for the branch to compile successfully. Will update the post if tests run successfully

- travis: https://travis-ci.org/NeroBurner/hunter/builds/466507513
- appveyor: https://ci.appveyor.com/project/NeroBurner/hunter/builds/20926741

**Comment by NeroBurner** [comment]
success!

**Comment by NeroBurner** [comment]
switched the branch, did the wrong base, just as with the glog PR :see_no_evil:

**Comment by ruslo** [comment]
No tests triggered here because `pkg.template` was the base originally and is excluded from testing.

Tests:
* https://ci.appveyor.com/project/ingenue/hunter/builds/20928892
* https://travis-ci.org/ingenue/hunter/builds/466542264?utm_source=github_status&utm_medium=notification

**Pull request merged**
