### PR TITLE
Pkg.lehrfempp

### PR DESCRIPTION
**Pull request by craffael**
* I have checked that this pull request contains only
  `.travis.yml`/`appveyor.yml` changes. All other changes send
  to https://github.com/ruslo/hunter. **Yes**

* I have checked that no toolchains removed from CI configs, they are commented
  out instead so other developers can enable them back easily and to simplify
  merge conflict resolution. **Yes**

* I have checked that for every commented out toolchain there is a link to the
  broken CI build page or to the minimum compiler requirements documentation
  so other developers can figure out what was the problem exactly. **Yes**

* I have checked that for every enabled toolchain corresponding package passed
  all stages of update cycle: test/merge/upload/release. **Yes**

### CODE REVIEW

**Comment by ruslo** [comment]
> craffael wants to merge 22 commits into **ingenue:pkg.template**

You should set `pkg.lehrfempp` as a destination, otherwise tests will not be run.

**Review by ruslo — CHANGES_REQUESTED** [review]
> Conflicting files
> appveyor.yml

Please resolve conflicts.

**Comment by craffael** [comment]
Okay I've resolved the merge conflict. 
For the next time you say that:

> You should set `pkg.lehrfempp` as a destination, otherwise tests will not be run.

But if I do 
```
git checkout pkg.template
git pull
git checkout pkg.lehrfempp
git merge pkg.template
git push origin pkg.lehrfempp
```
in order to get the latest build configs and I then create a merge request for craffael/pkg.lehrfempp -> ingenue/pkg.lehrfempp, that merge request will typically contain many changed files. But the PR template requires me to confirm "I have checked that this pull request contains only .travis.yml/appveyor.yml changes. All other changes send to https://github.com/ruslo/hunter." ?

**Comment by ruslo** [comment]
> But the PR template requires me to confirm

Yes, commits from `pkg.template` are fine too. Template updated:
- https://github.com/ingenue/hunter/blob/pkg.template/.github/PULL_REQUEST_TEMPLATE.md

**Review by ruslo — APPROVED** [review]

**Pull request merged**
